
version: "3.9"

services:

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb:inception
    environment:
      - DB_ROOT_PASSWD=${DB_ROOT_PASSWD:?err}
      - DB_WP_USER=${WP_ADMIN_USER:?err}
      - DB_WP_PASSWD=${WP_ADMIN_PASSWD:?err}
    volumes:
      - database:/data
    networks:
      - inception
    healthcheck:
      test: nc -z localhost 3306
      interval: 2s
      retries: 3
    restart: on-failure:3

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress:inception
    environment:
      - DB_WP_USER=${WP_ADMIN_USER:?err}
      - DB_WP_PASSWD=${WP_ADMIN_PASSWD:?err}
      - WP_ADMIN_USER=${WP_ADMIN_USER:?err} 
      - WP_ADMIN_PASSWD=${WP_ADMIN_PASSWD:?err} 
      - WP_USER_NAME=${WP_USER_NAME:?err} 
      - WP_USER_PASSWD=${WP_USER_PASSWD:?err} 
    volumes:
      - wordpress:/wordpress
    networks:
      - inception
    depends_on:
      mariadb:
        condition: service_healthy
    restart: on-failure:3

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx:inception
    volumes:
      - wordpress:/wordpress
    networks:
      - inception
    ports:
      - "8080:443"
    depends_on:
      - wordpress
    restart: on-failure:3

volumes:

  database:
    name: database 

  wordpress:
    name: wordpress

networks:

  inception:
    name: inception


